package com.ghreporter.api

import com.ghreporter.GHReporter
import com.ghreporter.api.models.CreateGistRequest
import com.ghreporter.api.models.GistFile
import com.ghreporter.api.models.GistResponse
import com.ghreporter.auth.SecureTokenStorage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.text.SimpleDateFormat
import java.util.*

/**
 * Service for creating GitHub Gists to store logs.
 *
 * Creates private Gists containing Timber logs, OkHttp logs, and Logcat output.
 */
class GistService(
    private val tokenStorage: SecureTokenStorage
) {

    private val apiService: GitHubApiService by lazy {
        GitHubApiClient.create(tokenStorage)
    }

    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US)
    private val filenameDateFormat = SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US)

    /**
     * Result of a Gist creation attempt.
     */
    sealed class GistResult {
        data class Success(val gist: GistResponse) : GistResult()
        data class Error(val message: String, val exception: Exception? = null) : GistResult()
    }

    /**
     * Create a private Gist with the provided log content.
     *
     * @param timberLogs Timber log content (or null to skip)
     * @param okHttpLogs OkHttp log content (or null to skip)
     * @param logcatLogs Logcat content (or null to skip)
     * @param screenshotBase64 Base64 encoded screenshot (or null to skip)
     * @param issueTitle Title of the related issue (for Gist description)
     * @return GistResult indicating success or failure
     */
    suspend fun createLogsGist(
        timberLogs: String?,
        okHttpLogs: String?,
        logcatLogs: String?,
        screenshotBase64: String? = null,
        issueTitle: String
    ): GistResult = withContext(Dispatchers.IO) {
        try {
            val files = mutableMapOf<String, GistFile>()
            val timestamp = dateFormat.format(Date())

            // Add Timber logs if present
            if (!timberLogs.isNullOrBlank()) {
                files["timber_logs.txt"] = GistFile(
                    content = buildFileHeader("Timber Logs", timestamp) + timberLogs
                )
            }

            // Add OkHttp logs if present
            if (!okHttpLogs.isNullOrBlank()) {
                files["network_logs.txt"] = GistFile(
                    content = buildFileHeader("Network Logs (OkHttp)", timestamp) + okHttpLogs
                )
            }

            // Add Logcat if present
            if (!logcatLogs.isNullOrBlank()) {
                files["logcat.txt"] = GistFile(
                    content = buildFileHeader("Logcat Output", timestamp) + logcatLogs
                )
            }

            // Add screenshot if present (as HTML file with embedded image)
            if (!screenshotBase64.isNullOrBlank()) {
                files["screenshot.html"] = GistFile(
                    content = buildScreenshotHtml(screenshotBase64, timestamp)
                )
            }

            if (files.isEmpty()) {
                return@withContext GistResult.Error("No logs to upload")
            }

            // Add a summary file with repo name and timestamp in filename
            val repoName = GHReporter.getConfig().githubRepo
            val filenameTimestamp = filenameDateFormat.format(Date())
            val summaryFilename = "${repoName}_${filenameTimestamp}.md"
            
            files[summaryFilename] = GistFile(
                content = buildSummaryFile(issueTitle, timestamp, files.keys.toList(), summaryFilename)
            )

            val request = CreateGistRequest(
                description = "Logs for: $issueTitle - Generated by GHReporter at $timestamp",
                public = false, // Private Gist
                files = files
            )

            val response = apiService.createGist(request)

            if (response.isSuccessful) {
                val gist = response.body()
                if (gist != null) {
                    GistResult.Success(gist)
                } else {
                    GistResult.Error("Empty response from GitHub API")
                }
            } else {
                val errorBody = response.errorBody()?.string()
                GistResult.Error(
                    "Failed to create Gist: ${response.code()} - ${errorBody ?: response.message()}"
                )
            }
        } catch (e: Exception) {
            GistResult.Error("Failed to create Gist: ${e.message}", e)
        }
    }

    /**
     * Convenience method to create a Gist from collected logs.
     *
     * @param includeTimber Whether to include Timber logs
     * @param includeOkHttp Whether to include OkHttp logs
     * @param includeLogcat Whether to include Logcat
     * @param screenshotBase64 Base64 encoded screenshot (or null to skip)
     * @param issueTitle Title of the related issue
     * @return GistResult
     */
    suspend fun createLogsGistFromCollectors(
        includeTimber: Boolean,
        includeOkHttp: Boolean,
        includeLogcat: Boolean,
        screenshotBase64: String? = null,
        issueTitle: String
    ): GistResult {
        val timberLogs = if (includeTimber) {
            GHReporter.getTimberLogs().takeIf { it.isNotEmpty() }
                ?.joinToString("\n") { it.format() }
        } else null

        val okHttpLogs = if (includeOkHttp) {
            GHReporter.getNetworkLogs().takeIf { it.isNotEmpty() }
                ?.joinToString("\n\n") { it.formatDetailed() }
        } else null

        val logcatLogs = if (includeLogcat) {
            GHReporter.collectLogcat().takeIf { it.isNotBlank() }
        } else null

        return createLogsGist(timberLogs, okHttpLogs, logcatLogs, screenshotBase64, issueTitle)
    }

    private fun buildFileHeader(title: String, timestamp: String): String {
        return """
            |================================================================================
            | $title
            | Generated: $timestamp
            | SDK: GHReporter for Android
            |================================================================================
            |
            |""".trimMargin()
    }

    private fun buildSummaryFile(
        issueTitle: String,
        timestamp: String,
        fileNames: List<String>,
        summaryFilename: String
    ): String {
        return """
            |# Log Files Summary
            |
            |**Issue:** $issueTitle
            |**Generated:** $timestamp
            |**SDK:** GHReporter for Android
            |
            |## Included Files
            |
            |${fileNames.filter { it != summaryFilename }.joinToString("\n") { "- `$it`" }}
            |
            |---
            |*This Gist was automatically generated by [GHReporter](https://github.com/your-repo/gh-reporter)*
            |""".trimMargin()
    }

    private fun buildScreenshotHtml(base64: String, timestamp: String): String {
        return """
            |<!DOCTYPE html>
            |<html>
            |<head>
            |    <title>Screenshot - GHReporter</title>
            |    <style>
            |        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 20px; background: #f6f8fa; }
            |        .container { max-width: 600px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
            |        h1 { font-size: 18px; color: #24292f; }
            |        .meta { color: #656d76; font-size: 12px; margin-bottom: 16px; }
            |        img { max-width: 100%; height: auto; border: 1px solid #d0d7de; border-radius: 4px; }
            |    </style>
            |</head>
            |<body>
            |    <div class="container">
            |        <h1>Screenshot</h1>
            |        <p class="meta">Generated: $timestamp | SDK: GHReporter for Android</p>
            |        <img src="data:image/jpeg;base64,$base64" alt="Screenshot" />
            |    </div>
            |</body>
            |</html>
            |""".trimMargin()
    }

    companion object {
        @Volatile
        private var instance: GistService? = null

        /**
         * Get singleton instance.
         */
        fun getInstance(tokenStorage: SecureTokenStorage): GistService {
            return instance ?: synchronized(this) {
                instance ?: GistService(tokenStorage).also {
                    instance = it
                }
            }
        }
    }
}
